version: 2.1
jobs:
    build:
        machine: true
        steps:
          ## install more recent version of docker-compose                                                  
          - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(\
uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          - run: sudo chmod a+x /usr/local/bin/docker-compose

          ## build 
          - checkout
          - run: cd ./yocto && docker-compose -f ./docker-compose.yml run --rm sifive-linux /usr/local/bin/build.sh --runall=fetch

