version: 2.1
jobs:
    build:
        machine: true
        steps:
          ## recently circleci:git complained about this (...)
          - run: git config --global user.email "l.rubusch@gmail.com"
          - run: git config --global user.name "Lothar Rubusch"
          - run: git config --global color.ui false

          ## install more recent version of docker-compose
          - run: sudo curl -L "https://github.com/docker/compose/releases/download/1.28.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          - run: sudo chmod a+x /usr/local/bin/docker-compose

          ## build
          - checkout
          - run: cd ./yocto && docker-compose up --exit-code-from sifive-unmatched
          ## due to ci time limitation, run a fetch all instead of build all

