version: 2.1
jobs:
    build:
        machine: true
        steps:
          ## recently circleci:git complained about this (...)
          - run: git config --global user.email "l.rubusch@gmail.com"
          - run: git config --global user.name "Lothar Rubusch"
          - run: git config --global color.ui false

          ## tools
          - run: apt-get update && apt-get install -y libffi-dev libssl-dev python3-dev python3 python3-pip
          - run: pip3 install docker-compose

          ## build
          - checkout
          - run: ./docker-setup.sh ci

