version: '3.8'

services:
    sifive-unmatched:
        container_name: sifive-unmatched
        image: ${USER}/sifive-unmatched
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: "${USER}"
                UID: "${UID}"
                GID: "${GID}"
        user: "${UID}:${GID}"
        stdin_open: true          ## docker run -i
        tty: true                 ## docker run -t
        #privileged: true
        environment:
         - USER
        env_file:
         - .env
        volumes:
         ## folders not need to be around
         - ~/.gitconfig:/home/$USER/.gitconfig
         - ~/.ssh:/home/$USER/.ssh
         - ./poky:/home/$USER/poky
         ## folder must be around
         - type: bind
           source: ./build_configs
           target: /home/$USER/configs
